name: TEST
favicon: null
layout_spectrum: 0.22067
typography_spectrum: 0.3351254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2dce8'
    - '#132529'
    - '#a4a4ac'
    - '#e0833d'
    - '#616b6c'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
