favicon: null
name: TEST
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3996416
  brandStrength: 0.3125
  lightness: 0.7849463
  brandColors:
    - '#e2dce8'
    - '#132529'
    - '#a4a4ac'
    - '#e0833d'
    - '#616b6c'
  rhythmicContrast: 0.6272401
typography_spectrum: 0.1541219
layout_spectrum: 0.9982079
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
